server-name: "HCFactions"

LICENSE_KEY:
  - "penisEnlargmentPillsDoWork"

redis:
  host: "localhost"
  port: 6379
  channel: "staffutils"
  auth:
    enabled: false
    password: "mysecret"

report-formatting:
  - "&eReported Player:&d %player%"
  - "&eReporter Name:&d %reporterName%"
  - "&eReason:&d %reason%"
  - "&eServer:&d %server%"

request-formatting:
  - "&eRequested Player:&d %player%"
  - "&eReason:&d %reason%"
  - "&eServer:&d %server%"

staffchat-formatting:
  - "&b(%server%)&e %player%: %message%"

serverswitch-formatting:
  - "&b(Staff) %player%: &7has changed server: %status% : %server%"

clearchat-formatting:
  - "&cChat has been cleared by %clearName%"

staffmode.compass.name: "&cTeleport Compass"
staffmode.compass.slot: 0

staffmode.book.name: "&cInspection Book"
staffmode.book.slot: 1

staffmode.followplayer.name: "&cFollow Player"
staffmode.followplayer.slot: 2

staffmode.carpet.name: "&cBetter Look"
staffmode.carpet.slot: 4

staffmode.randomteleport.name: "&CRandom Teleport"
staffmode.randomteleport.slot: 8