name: StaffUtilities
main: site.solenxia.staffutilities.StaffUtilities
version: -0.1-BETA1
author: GregoryG, Sergii
commands:
 report:
 staffchat:
  aliases: [sc]
 mutechat:
  aliases: [mc]
 request:
  aliases: [helpop]
 clearchat:
  aliases: [cc]
 vanish:
  aliases: [v]
 staffmode:
  aliases: [mod, h]